#!env python3
"""
Basic Shell Player 
"""
# Local HackaGame:
from hackapy.player import PlayerIHM as Player
from hackapy.command import Command, Option

# Define a command interpreter: 2 options: host address and port:
cmd= Command(
    "connect",
    [
        Option( "host", "h", default="localhost" ),
        Option( "port", "p", default=1400 )
    ],
    "connect a game server. No ARGUMENT"
)

# Process the command line: 
cmd.process()

if not cmd.ready() :
    print( cmd.help() )
    exit()

# Start the player the command line: 
print('let\'s go...')
player= Player()
results= player.takeASeat( cmd.option('host'), cmd.option('port') )
print( f"Average: { float(sum(results))/len(results) }" )
