#!env python3
"""
HackaGame - Game - 421 
"""
import sys, os

sys.path.insert(1, os.path.join(sys.path[0], '../..'))

import gameEngine as g421
from hackapy.player import PlayerIHM as Player

def main():
    game= g421.GameSolo()
    game.local( [Player()], 1 )

# script
if __name__ == '__main__' :
    main()