#!env python3
"""
HackaGame - Game - 421 
"""
import sys, os

sys.path.insert(1, os.path.join(sys.path[0], '..'))

from gameEngine import GameSolo as Game
from hackapy.player import PlayerIHM as Player

def main():
  game= Game()
  player1= Player()
  game.local( [player1], 1 )

# script
if __name__ == '__main__' :
    main()