#!env python3
"""
HackaGame - Game - TicTacToe 
"""
import gameEngine as gttt
from terminalIHM import TTTPlayer as Player1
from classicFirstAI import PlayerRandom as Player2

def main():
    game= gttt.GameTTT( "classic" )
    player1= Player1()
    player2= Player2()
    game.local( [player1, player2], 1 )

# script
if __name__ == '__main__' :
    main()