#!env python3
"""
HackaGame - Game - TicTacToe 
"""

import sys

import gameEngine as gttt
from playerInteractive import PlayerShell as Player
from playerFirstAI import AutonomousPlayer as Oponent

def main():
    shArgs= sys.argv
    mode= "classic"
    if len(shArgs) > 1 and shArgs[1] in ["ultimate", "Ultimate", "u", "U"] :
        mode= "ultimate"
    game= gttt.GameTTT( mode )
    player1= Player()
    player2= Oponent()
    game.local( [player1, player2], 1 )

# script
if __name__ == '__main__' :
    main()