#!env python3
"""
HackaGame - Game - TicTacToe 
"""
from gameEngine import GameRisky
from terminalIHM import RiskyPlayer as Player1
# from classicFirstAI import PlayerRandom as Player2

def main():
    game= GameRisky( 2, "board-4" )
    game.local( [Player1(), Player1()], 1 )

# script
if __name__ == '__main__' :
    main()
