#!env python3
"""
HackaGame - Game - TicTacToe 
"""
from gameEngine import GameRisky
from terminalIHM import RiskyPlayer as Player1
from firstAI import PlayerRandom as Player2

def main():
    game= GameRisky( 2, "board-6" )
    game.local( [Player2(), Player1()], 1 )

# script
if __name__ == '__main__' :
    main()
