#!env python3
"""
HackaGame - Game - TicTacToe 
"""
from gameEngine import GameRisky
from terminalIHM import RiskyPlayer as Player1
from firstAI import PlayerRandom as Player2

def main():
    game= GameRisky( 2, "board-10" )
    player1= Player2()
    player2= Player1()
    game.local( [player1, player2], 1 )

# script
if __name__ == '__main__' :
    main()
