#!env python3
"""
HackaGame - Game - Risky
"""
from gameEngine import GameRisky
from gameEngine.players import PlayerShell as Player1
from gameEngine.players import PlayerRandom as Player2

def main():
    game= GameRisky( 2, "board-4" )
    player1= Player2()
    player2= Player1()
    game.local( [player1, player2], 1 )

# script
if __name__ == '__main__' :
    main()
