#!env python3
"""
HackaGame - Game - Py421 
"""

import sys
sys.path.insert( 1, __file__.split('gamePy421')[0] )

from gamePy421.gameEngine import GameSolo
from hackapy.player import PlayerIHM as Player

def main():
  game= GameSolo()
  player1= Player()
  game.local( [player1], 1 )

# script
if __name__ == '__main__' :
    main()
