#!env python3
"""
HackaGame - Game - Py421 
"""

import sys
sys.path.insert( 1, __file__.split('gamePy421')[0] )

from gamePy421.gameEngine import GameSolo, GameDuo
from hackapy.player import PlayerIHM as Player
from hackapy.command import Command, Option
from gamePy421.playerFirstAI import AutonomousPlayer as Opponent

# Define a command interpreter: 2 options: host address and port:
cmd= Command(
    "start-interactive",
    [
        Option( "number", "n", 1, "number of games" )
    ],
    "Start interactive gamePy421. ARGUMENTS can be: solo or duo" )
# Process the command line: 
cmd.process()
if not cmd.ready() :
    print( cmd.help() )
    exit()

# Start the player the command line: 
if cmd.argument() == "duo" :
  game= GameDuo()
  player1= Player()
  game.local( [player1, Opponent()], cmd.option("number") )  
else :
  game= GameSolo()
  player1= Player()
  game.local( [player1], cmd.option("number") )
