#!env python3
"""
HackaGame - Game - 421 
"""
import sys

# Local HackaGame:
sys.path.insert( 1, __file__.split('gamePy421')[0] )
from hackapy.command import Command, Option
import gameEngine as g421

# Commands:
cmd= Command(
        "start-server",
        [
            Option( "port", "p", default=1400 ),
            Option( "number", "n", 2, "number of games" )
        ],
        (
            "star a server fo gamePy421 on your machine. "
            "ARGUMENTS refers to game mode: solo or duo."
        ))
cmd.process()
if cmd.ready() :
    if cmd.argument() == "duo" :
        game= g421.GameDuo()
    else :
        game= g421.GameSolo()
else :
    print( cmd.help() )
    exit()

# start:
game.start( cmd.option("number"), cmd.option("port") )
